### ISSUE TITLE
Błąd dla addPackage()

### ISSUE THREAD

**Issue by tomasz-kusy** [Kwarcek/furgonetka-rest-api-php#4]
Witam,
Testowano dla Inpost.

Dostaję taki błąd: "{"errors":[{"path":"/sender","message":"Inne dane na etykiecie nie są dostępne dla wybranego przewoźnika","details":"","code":"name"}]}"

Okazuje się, że winne jest wymaganie przeyłania struktury "sender". Po umożliwieniu przekazywania null (jako parametr sender) błąd ustępuje.

Nie chcę pochopnie robić pull requesta, ale wydaje mi się, że to jest błąd.

**Comment by Kwarcek** [comment]
Witam,
Podaj proszę więcej szczegółów jakie dane wysyłasz, dane wrażliwe możesz zmienić na Jan Kowalski etc. 
Dokumentacja API: https://furgonetka.pl/api/rest#tag/Przesylki/operation/packages-post

**Comment by tomasz-kusy** [comment]
Zadam pytanie:
Dlaczego np. tutaj https://github.com/Kwarcek/furgonetka-rest-api-php/blob/ff860b3f41dbcbdaed8f37548f7c31ea34631b61/src/Request/PackageRequest.php#L415 wymagasz encji $sender, chociaż zgodnie z dokumentacją nie jest wymagana?
Przekazanie null rozwiązuje problem.
Zgodnie z dokumentacją serwisu:
_Struktura zawierająca dane, które znajdą się na etykiecie. Dostępna dla przewoźników: DPD, DHL, FedEx, UPS, InPost Kurier._

Ja testuję dla Inpost (nie Inpost Kuier). Stąd błąd.

**Comment by Kwarcek** [comment]
Masz rację, dzisiaj wieczorem wyślę poprawkę, dzięki za uwagę!

**Comment by tomasz-kusy** [comment]
Dzięki. Problem występuje jeszcze w innych miejscach (np. validate()). Poprawiłem + parę dołożyłem innych drobnych, ale chyba istotnych, poprawek.
Nie chciałem przeorywać testów (lokalnie to zrobiłem), ale nie działają, bo nie ma takich serviceId. Nie wiem czy każdy ma inne (np. Inpost Paczkomaty u mnie to 9592971), czy tylko się zmieniły. Tak czy inaczej chyba warto je sparametryzować.

**Comment by Kwarcek** [comment]
Dzięki za wkład! MR zmergowany. Co do `serviceId` to podczas robienia tej paczki w wersji v1 wszystko jak najbardziej działało, brałem pod uwagę, że w przyszłości te `serviceId` mogą się zmienić i w samej paczce nie są nigdzie zamapowane, nie ma żadnych `enum` ani nic takiego - do zwracania `serviceId` furgonetka zwraca endpoint i tego bym się trzymał.
